[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"
watchPatterns = ["**"]

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
